name: Check

on:
  push:
    branches:
    - main

jobs:
  ui:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Print Message
      run: echo "Hello, GitHub Actions!"
    - name: Test Secret
      run: echo $AWS_ACCESS_KEY
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
