name: Check

on:
  push:
    branches:
    - main

env:
  NODE_ENV: production
  PORT: 5000
jobs:
  ui:
    name: Test
    runs-on: ubuntu-latest
    env:
     name_user: Tharun
    steps:
    - name: Print Message
      run: echo "Hello, GitHub Actions!"
    - run: echo $NODE_ENV
    -  run: echo $PORT
    - name: Test Secret
      run: echo $AWS_ACCESS_KEY
    - name: useranme name_user
      run: echo $name_user
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
