name: Check

on:
  push:
    branches:
      - main

# Workflow Level
env:
  NODE_ENV: production
  PORT: 5000

jobs:
# buildApplication
  buildApplication:    #Jobname
    runs-on: ubuntu-latest    # runs on machine

    # Job Level
    env:
      name_user: Tharun
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}

    steps:
      - name: Print Message
        run: echo "Hello, GitHub Actions!"

      - name: Print Workflow Env
        run: |
          echo $NODE_ENV
          echo $PORT

      - name: Print Secret
        run: echo $AWS_ACCESS_KEY

      - name: Print Job Env
        run: echo $name_user