name: Chek
on:
push:
branch:
- main


jobs:
 ui:
   name: Test
   runs-on: ubuntu-latest


   steps:
   - name: check teh ymal file
     run : echo "hi"
   - name: check teh ymal file
     run : echo "hi"